### PR TITLE
Allow to display formatted values in the funnel.

### PR DESCRIPTION
**Pull request by stefanwalther**
This pull request allows to pass in formatted values to be displayed:

```javascript
var data = [
   ["Teal",      [12000, 'USD 12,000'], "#008080"],
   ["Byzantium", [4000, 'USD 4,000'],  "#702963"],
   ["Persimmon", [2500, 'USD 2,500'],  "#ff634d"],
   ["Azure",     [1500, 'USD 1,500'],  "#007fff"]
];
```

Sorry for distroying the format (indenting) of the index.html ... see the other issue I have posted, hope you can add a .editorconfig then this cannot happen that easily ;-)

Regards
Stefan

### CODE REVIEW

**Comment by jakezatecky** [comment]
`.editorconfig` added in #17.

I appreciate the PR, but I'll leave this standing for a while (partially due to the formatting, but mostly due to my response in #16).

**Comment by stefanwalther** [comment]
I'd certainly fix the formatting issue if you want, but will also answer to your concerns in #16

**Comment by jakezatecky** [comment]
If you adjust the example HTML file back to the original style, I can go ahead and merge this request. I'll work on supporting another approach when I have the time.

**Comment by stefanwalther** [comment]
OK; will do so ...

**Comment by stefanwalther** [comment]
Closed because of formatting issues, opened #20 instead.

**Pull request closed without merging**
